import type { Car } from "./types";

export const DB: Car[] = [
  {
    title: "Cadet",
    type: "car",
    scale: "1:64",
    origin: "Zuru",
    treasureHunt: false,
    series: "Metal Machines",
    order: "",
    year: 0,
    mainMaterial: "metal",
  },
  {
    title: "Batman: The Animated Series",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "Batman",
    order: "5/5",
    year: 0,
    mainMaterial: "metal",
    image: "31.jpg",
  },
  {
    title: "Mazda Repu",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "HW Hot Trucks",
    order: "2/10",
    year: 0,
    mainMaterial: "metal",
  },
  {
    title: "'73 BMW 3.0 CLS Race Car",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "Retro Racers",
    order: "2/10",
    year: 2021,
    mainMaterial: "metal",
  },
  {
    title: "Time Shifter",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "HW Metro",
    order: "2/10",
    year: 2021,
    mainMaterial: "metal",
    image: "17.jpg",
  },
  {
    title: "'70 Chevy Chevelle",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "HW Contored",
    order: "3/5",
    year: 0,
    mainMaterial: "metal",
    image: "18.jpg",
  },
  {
    title: "'87 Ford Sierra Cosworth",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "Retro Racers",
    order: "1/10",
    year: 2022,
    mainMaterial: "metal",
  },
  {
    title: "'84 Mustang SVO",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "HW: The '80s",
    order: "2/10",
    year: 2022,
    mainMaterial: "metal",
  },
  {
    title: "'49 Ford F1",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "Pro Squad",
    order: "5/10",
    year: 2019,
    mainMaterial: "metal",
    image: "35.jpg",
  },
  {
    title: "Mod Rod",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "HW Dream Garage",
    order: "5/10",
    year: 2019,
    mainMaterial: "metal",
    image: "32.jpg",
  },
  {
    title: "Circle Tracker",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "HW Race day",
    order: "6/10",
    year: 2019,
    mainMaterial: "metal",
    image: "36.jpg",
  },
  {
    title: "Snoopi",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "HW Screen Time",
    order: "5/10",
    year: 2018,
    mainMaterial: "metal",
    image: "19.webp",
  },
  {
    title: "Paty Wagon (TMNT)",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "HW Screen Time",
    order: "3/10",
    year: 2020,
    mainMaterial: "metal",
    image: "20.jpg",
  },
  {
    title: "'52 Hudson Hornet (Purple)",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "Pro Squad",
    order: "4/10",
    year: 2020,
    mainMaterial: "metal",
    image: "21.jpg",
  },
  {
    title: "'73 Ford Falcon XB (Green)",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "HW Flames",
    order: "7/10",
    year: 2020,
    mainMaterial: "metal",
    image: "22.jpg",
  },
  {
    title: "'71 Plymouth GTX",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "Muscle Mania",
    order: "7/10",
    year: 2023,
    mainMaterial: "metal",
    image: "33.webp",
  },
  {
    title: "'55 Chevy Bel Air Gasser (Purple)",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "Chevy Bel Air",
    order: "2/5",
    year: 2022,
    mainMaterial: "metal",
    image: "23.jpg",
  },
  {
    title: "Arkham Asylum Batmobile (Blue)",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: true,
    series: "Batman",
    order: "5/5",
    year: 2019,
    mainMaterial: "metal",
    image: "24.jpg",
  },
  {
    title: "Arkham Asylum Batmobile (Green)",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "Batman",
    order: "2/5",
    year: 2020,
    mainMaterial: "metal",
    image: "25.jpg",
  },
  {
    title: "The Batman Batmobile (Blue)",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "Batman",
    order: "2/5",
    year: 2020,
    mainMaterial: "metal",
    image: "26.jpg",
  },
  {
    title: "Batmobile (Chrome)",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "Batman",
    order: "3/5",
    year: 2020,
    mainMaterial: "metal",
    image: "27.jpg",
  },
  {
    title: "Arkham Knight Batmobile (Red)",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "Batman",
    order: "1/5",
    year: 2020,
    mainMaterial: "metal",
    image: "28.jpg",
  },
  {
    title: "Batman 2022 Batmobile",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "DC Character Cars",
    order: "",
    year: 2022,
    mainMaterial: "metal",
    image: "29.jpg",
  },
  {
    title: "Batplane (Black)",
    type: "plane",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "Batman",
    order: "1/5",
    year: 2020,
    mainMaterial: "metal",
    image: "30.jpg",
  },
  {
    title: "'10 Pro Stock Camaro",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "HW Speed Graphics",
    order: "5/10",
    year: 2018,
    mainMaterial: "metal",
  },
  {
    title: "Porsche 934 Turbo RSR",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "Forza Motorsport",
    order: "5/5",
    year: 2020,
    mainMaterial: "metal",
    image: "16.jpg",
  },
  {
    title: "Ford Shelby GT350",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "Forza Motorsport",
    order: "4/5",
    year: 2020,
    mainMaterial: "metal",
    image: "15.webp",
  },
  {
    title: "X-Jet (Blue)",
    type: "plane",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "HW Screen Time",
    order: "10/10",
    year: 2021,
    mainMaterial: "metal",
    image: "14.jpg",
  },
  {
    title: "X-Jet (Black)",
    type: "plane",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "HW Screen Time",
    order: "4/40",
    year: 2021,
    mainMaterial: "metal",
    image: "13.jpg",
  },
  {
    title: "Tricera-Truck (Teal)",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "Dino Reders",
    order: "3/5",
    year: 2021,
    mainMaterial: "metal",
    image: "12.jpg",
  },
  {
    title: "Volkswagen Beetle (Green)",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "Compact Kings",
    order: "2/5",
    year: 2022,
    mainMaterial: "metal",
    image: "11.jpg",
  },
  {
    title: "'55 Chevy (Red)",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "Chevy Bel Air",
    order: "1/5",
    year: 2022,
    mainMaterial: "metal",
    image: "37.jpg",
  },
  {
    title: "TV Series Batmobile",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "Batman",
    order: "4/5",
    year: 2022,
    mainMaterial: "metal",
  },
  {
    title: "Jeep Wrangler",
    type: "car",
    scale: "1:34-1:39",
    origin: "Welly",
    treasureHunt: false,
    series: "",
    order: "#8890",
    year: 0,
    mainMaterial: "metal",
  },
  {
    title: "Mercedes-Benz CLK-GTR",
    type: "car",
    scale: "1:34-1:39",
    origin: "Welly",
    treasureHunt: false,
    series: "",
    order: "#9746",
    year: 0,
    mainMaterial: "metal",
    image: "39.jpg",
  },
  {
    title: "Chrysler Crossfire",
    type: "car",
    scale: "1:43",
    origin: "Max Motor",
    treasureHunt: false,
    series: "",
    order: "#4046",
    year: 2003,
    mainMaterial: "metal",
    image: "40.jpg",
  },
  {
    title: "Ford Mustang 1999",
    type: "car",
    scale: "1:34-1:39",
    origin: "Welly",
    treasureHunt: false,
    series: "",
    order: "#9753",
    year: 0,
    mainMaterial: "metal",
    image: "38.webp",
  },
  {
    title: "Roadbeasts McDonald's",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "",
    order: "",
    year: 2003,
    mainMaterial: "metal",
    image: "10.png",
  },
  {
    title: "'17 Acura NSX",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "Forza Motorsport",
    order: "2/5",
    year: 2020,
    mainMaterial: "metal",
    image: "9.webp",
  },
  {
    title: "Pink 5",
    type: "car",
    scale: "1:64",
    origin: "China",
    treasureHunt: false,
    series: "",
    order: "",
    year: 2000,
    mainMaterial: "metal",
  },
  {
    title: "Police Car",
    type: "car",
    scale: "1:64",
    origin: "China",
    treasureHunt: false,
    series: "",
    order: "",
    year: 2000,
    mainMaterial: "plastic",
  },
  {
    title: "Cargo Car",
    type: "car",
    scale: "1:64",
    origin: "China",
    treasureHunt: false,
    series: "",
    order: "",
    year: 2000,
    mainMaterial: "metal",
  },
  {
    title: "Ford Mustang Mach-E 140",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "HW Green Speed",
    order: "1/5",
    year: 2021,
    mainMaterial: "metal",
    image: "34.jpg",
  },
  {
    title: "McLaren F1 GTR",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "Retro Racers",
    order: "3/10",
    year: 2021,
    mainMaterial: "metal",
    image: "8.webp",
  },
  {
    title: "'57 Chevy",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "Chevy Bel Air",
    order: "3/5",
    year: 2021,
    mainMaterial: "metal",
  },
  {
    title: "Subaru WRX STI",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "HW Hatchbacks",
    order: "4/5",
    year: 2021,
    mainMaterial: "metal",
  },
  {
    title: "Nissan Skyline GT-R (R32)",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "J-Imports",
    order: "5/10",
    year: 2021,
    mainMaterial: "metal",
    image: "7.webp",
  },
  {
    title: "'32 Ford",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "Retro Racers",
    order: "2/10",
    year: 2021,
    mainMaterial: "metal",
    image: "6.jpg",
  },
  {
    title: "'83 Chevy Silverado",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "",
    order: "1/5",
    year: 2025,
    mainMaterial: "metal",
    image: "2.jpg",
  },
  {
    title: "Purple Passion",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "",
    order: "",
    year: 2025,
    mainMaterial: "metal",
    image: "5.webp",
  },
  {
    title: "'57 GMC Stepside",
    type: "car",
    scale: "1:64",
    origin: "Match Box",
    treasureHunt: false,
    series: "",
    order: "",
    year: 2025,
    mainMaterial: "metal",
    image: "1.jpg",
  },
  {
    title: "'82 Toyota Supra ",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "HW: The '80s",
    order: "10/10",
    year: 2024,
    mainMaterial: "metal",
    image: "3.webp",
  },
  {
    title: "1978 Dodge Li'l Red Express Truck",
    type: "car",
    scale: "1:64",
    origin: "Hot Wheels",
    treasureHunt: false,
    series: "",
    order: "",
    year: 2024,
    mainMaterial: "metal",
    image: "4.webp",
  },
];
